DROP TABLE IF EXISTS GROUP_DETAIL;
CREATE TABLE GROUP_DETAIL (
	ID BIGINT(20) NOT NULL,
	CHN VARCHAR(10) NOT NULL,
	LIBRARY_NAME1 VARCHAR(50) NOT NULL,
	LIBRARY_NAME2 VARCHAR(50) NOT NULL,
	FEATURE_ID VARCHAR(50) NOT NULL,
	PEOPLE_ID VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	X INT(11) NOT NULL,
	Y INT(11) NOT NULL,
	UPDATED_ON BIGINT(20) NOT NULL,
	BIO_SUBTYPE INT(11) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX FEATURE ON GROUP_DETAIL(CHN, LIBRARY_NAME1, LIBRARY_NAME2, FEATURE_ID);
CREATE INDEX PEOPLE ON GROUP_DETAIL(PEOPLE_ID,CATEGORY);

CREATE INDEX LIBRARY_NAME ON GROUP_DETAIL(CHN, LIBRARY_NAME1, LIBRARY_NAME2);
